---
- name: Add User
  hosts: all
  vars_files: /root/ansible-project1/variables/dev_vars.yaml
  gather_facts: "{{ facts }}"
  tasks:
    - name: add user bob
      user:
        name: "{{ username }}"
        uid: "{{ uid }}"