---
- name: Install Packages
  hosts: all
  vars:
    packages:
      - curl
      - wget
      - git
      - tree
      - epel-release
    facts: true
  gather_facts: "{{ facts }}"
  tasks:
    - name: Install Packages
      when: packages is defined
      yum:
        name: "{{ packages }}"
        state: latest 