---
- name: Ping Server
  hosts: host1
  vars:
    key1: "value1"
    key2: "value2"
  gather_facts: False
  tasks:
    - name: Ping
      ping:
    
    - name: Print variables
      when: ansible_distribution is defined
      debug:
        msg: "OS = {{ ansible_distribution }}"