---
- name: Ping Server
  hosts: host1
  vars:
    key1: "value1"
    key2: "value2"
  tasks:
    - name: Ping
      ping:
    
    - name: Print variables
      debug:
        msg: "{{ key1 }} {{ key2 }}"